### ISSUE TITLE
Output units wrong Mb/s -> MiB/s

### ISSUE THREAD

**Issue by mulbc** [IBM/k8s-storage-perf#20]
The output of sysbench is in MiB/s not Mb/s. We need to change this in the output of this tool too

**Comment by datapresso** [comment]
Knowledge Center is referencing 11 MB/s for CP4D, should it be 11 MiB instead? https://www.ibm.com/docs/en/cloud-paks/cp-data/4.7.x?topic=requirements-hardware#hardware-reqs__disk @bxu1999

**Comment by bxu1999** [comment]
Okay, I've updated this project's output `result.csv` to use `MiB/s`, but we believe that inherently the underlying container produces the result json files with field keys using `Mb/s`. We'll have to dig into this a bit further when get a chance. For now, the issue raised here is fixed. Please check and review and provide your feedback.

![image](https://github.com/IBM/k8s-storage-perf/assets/3228732/5f6ae5ab-345e-40dd-9aab-ccc2e62efe1d)
