### ISSUE TITLE
test sysbench.py <fileExtraFlags> flag with "direct"

### ISSUE THREAD

**Issue by bxu1999** [IBM/k8s-storage-perf#29]
The sysbench.py <fileExtraFlags> flag is currently hard-coded with "dsync", and this is to test with the "direct" flag.

**Comment by bxu1999** [comment]
A parameter for this has been added:

```
file_extra_flags: dsync
```
The value can be "dsync" or "direct"

**Comment by jeanchlopez** [comment]
My fork if the changes are merged have way more options than that @bxu1999. The other problem is that the `sync` flag although honored by the python script does not honor the other flags (`async` and `0`) that you have in the template file.
