### ISSUE TITLE
During initial perf test, seeing error about   "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!" 

### ISSUE THREAD

**Issue by jfengsun** [IBM/k8s-storage-perf#35]
Client's environment:
RHEL 7, python3.6, ansible 2.10.17

During initial perf test after setup, seeing error for multiple volumes:
`   "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!" `
Tried adding ansible_python_interpreter=/usr/bin/python3.6 into params.yaml but the error still there

**Comment by jfengsun** [comment]
Installed python3-libselinux on this RHEL7 host and resolved the issue

**Comment by shankarpentyala07** [comment]
For future reference, the resolution  is: https://stackoverflow.com/questions/63173955/aborting-target-uses-selinux-but-python-bindings-libselinux-python-arent-ins

**Comment by jfengsun** [comment]
This seems only happens on RHEL7, which by default has libselinux for python2 only

RHEL8 and above won't have the issue
