### ISSUE TITLE
Enhancement to support oc login with apikey

### ISSUE THREAD

**Issue by eling-ibm** [IBM/k8s-storage-perf#6]
Right now, the tool only support oc login with credential using user/password or token. It is very common to use apikey to login OCP cluster especially for ROKS clusters.

The enhancement request is to include the following oc login option while running IO perf testing on the cluster.
oc login -u apikey -p {ocp_apikey} --server={ocp_url}

**Comment by bxu1999** [comment]
Sure, will do. Thanks.

**Comment by bxu1999** [comment]
This enhancement has been implemented and delivered. Please follow the README to try it.

If you find any issue, reopen this git issue. Thanks.
