### ISSUE TITLE
typo in the docker instructions for seeing the results

### ISSUE THREAD

**Issue by jesusmah** [IBM/k8s-storage-perf#8]
In the documentation, when you go down the path of executing the tool within the container, to see the results there is the following instruction:

```
docker cp ${container_name}:/opt/ansible/storage-perf.tar /tmp/k8s_storage_perf/work-dir/data/storage-perf.tar
````

which fails if you use podam.

docker should be changed by `${dockerexe}`

**Comment by bxu1999** [comment]
fixed. Thanks.
